CREATE TABLE so.feature_types (id smallint PRIMARY KEY, qname text NOT NULL);
COMMENT ON TABLE so.feature_types IS 'Ids and bboxes of concrete feature types';
SELECT ADDGEOMETRYCOLUMN('so', 'feature_types','bbox','0','GEOMETRY',2);
INSERT INTO so.feature_types  (id,qname) VALUES (0,'{http://inspire.ec.europa.eu/schemas/ad/4.0}Address');
INSERT INTO so.feature_types  (id,qname) VALUES (1,'{http://inspire.ec.europa.eu/schemas/ad/4.0}AddressAreaName');
INSERT INTO so.feature_types  (id,qname) VALUES (2,'{http://inspire.ec.europa.eu/schemas/ad/4.0}AdminUnitName');
INSERT INTO so.feature_types  (id,qname) VALUES (3,'{http://inspire.ec.europa.eu/schemas/ad/4.0}PostalDescriptor');
INSERT INTO so.feature_types  (id,qname) VALUES (4,'{http://inspire.ec.europa.eu/schemas/ad/4.0}ThoroughfareName');
INSERT INTO so.feature_types  (id,qname) VALUES (5,'{http://inspire.ec.europa.eu/schemas/au/4.0}AdministrativeBoundary');
INSERT INTO so.feature_types  (id,qname) VALUES (6,'{http://inspire.ec.europa.eu/schemas/au/4.0}AdministrativeUnit');
INSERT INTO so.feature_types  (id,qname) VALUES (7,'{http://inspire.ec.europa.eu/schemas/au/4.0}Condominium');
INSERT INTO so.feature_types  (id,qname) VALUES (8,'{http://inspire.ec.europa.eu/schemas/base/3.3}SpatialDataSet');
INSERT INTO so.feature_types  (id,qname) VALUES (9,'{http://inspire.ec.europa.eu/schemas/cp/4.0}BasicPropertyUnit');
INSERT INTO so.feature_types  (id,qname) VALUES (10,'{http://inspire.ec.europa.eu/schemas/cp/4.0}CadastralBoundary');
INSERT INTO so.feature_types  (id,qname) VALUES (11,'{http://inspire.ec.europa.eu/schemas/cp/4.0}CadastralParcel');
INSERT INTO so.feature_types  (id,qname) VALUES (12,'{http://inspire.ec.europa.eu/schemas/cp/4.0}CadastralZoning');
INSERT INTO so.feature_types  (id,qname) VALUES (13,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}AnthropogenicGeomorphologicFeature');
INSERT INTO so.feature_types  (id,qname) VALUES (14,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}Borehole');
INSERT INTO so.feature_types  (id,qname) VALUES (15,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}Fold');
INSERT INTO so.feature_types  (id,qname) VALUES (16,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}GeologicCollection');
INSERT INTO so.feature_types  (id,qname) VALUES (17,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}GeologicEvent');
INSERT INTO so.feature_types  (id,qname) VALUES (18,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}GeologicUnit');
INSERT INTO so.feature_types  (id,qname) VALUES (19,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}MappedFeature');
INSERT INTO so.feature_types  (id,qname) VALUES (20,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}MappedInterval');
INSERT INTO so.feature_types  (id,qname) VALUES (21,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}NaturalGeomorphologicFeature');
INSERT INTO so.feature_types  (id,qname) VALUES (22,'{http://inspire.ec.europa.eu/schemas/ge-core/4.0}ShearDisplacementStructure');
INSERT INTO so.feature_types  (id,qname) VALUES (23,'{http://inspire.ec.europa.eu/schemas/ge_gp/4.0}Campaign');
INSERT INTO so.feature_types  (id,qname) VALUES (24,'{http://inspire.ec.europa.eu/schemas/ge_gp/4.0}GeophObjectSet');
INSERT INTO so.feature_types  (id,qname) VALUES (25,'{http://inspire.ec.europa.eu/schemas/ge_gp/4.0}GeophProfile');
INSERT INTO so.feature_types  (id,qname) VALUES (26,'{http://inspire.ec.europa.eu/schemas/ge_gp/4.0}GeophStation');
INSERT INTO so.feature_types  (id,qname) VALUES (27,'{http://inspire.ec.europa.eu/schemas/ge_gp/4.0}GeophSwath');
INSERT INTO so.feature_types  (id,qname) VALUES (28,'{http://inspire.ec.europa.eu/schemas/gn/4.0}NamedPlace');
INSERT INTO so.feature_types  (id,qname) VALUES (29,'{http://inspire.ec.europa.eu/schemas/net/4.0}CrossReference');
INSERT INTO so.feature_types  (id,qname) VALUES (30,'{http://inspire.ec.europa.eu/schemas/net/4.0}GradeSeparatedCrossing');
INSERT INTO so.feature_types  (id,qname) VALUES (31,'{http://inspire.ec.europa.eu/schemas/net/4.0}Network');
INSERT INTO so.feature_types  (id,qname) VALUES (32,'{http://inspire.ec.europa.eu/schemas/net/4.0}NetworkConnection');
INSERT INTO so.feature_types  (id,qname) VALUES (33,'{http://inspire.ec.europa.eu/schemas/ompr/3.0}Process');
INSERT INTO so.feature_types  (id,qname) VALUES (34,'{http://inspire.ec.europa.eu/schemas/ps/4.0}ProtectedSite');
INSERT INTO so.feature_types  (id,qname) VALUES (35,'{http://inspire.ec.europa.eu/schemas/so/4.0}DerivedSoilProfile');
INSERT INTO so.feature_types  (id,qname) VALUES (36,'{http://inspire.ec.europa.eu/schemas/so/4.0}ObservedSoilProfile');
INSERT INTO so.feature_types  (id,qname) VALUES (37,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilBody');
INSERT INTO so.feature_types  (id,qname) VALUES (38,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilDerivedObject');
INSERT INTO so.feature_types  (id,qname) VALUES (39,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilHorizon');
INSERT INTO so.feature_types  (id,qname) VALUES (40,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilLayer');
INSERT INTO so.feature_types  (id,qname) VALUES (41,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilPlot');
INSERT INTO so.feature_types  (id,qname) VALUES (42,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilSite');
INSERT INTO so.feature_types  (id,qname) VALUES (43,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilThemeCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (44,'{http://inspire.ec.europa.eu/schemas/so/4.0}SoilThemeDescriptiveCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (45,'{http://inspire.ec.europa.eu/schemas/tn/4.0}AccessRestriction');
INSERT INTO so.feature_types  (id,qname) VALUES (46,'{http://inspire.ec.europa.eu/schemas/tn/4.0}ConditionOfFacility');
INSERT INTO so.feature_types  (id,qname) VALUES (47,'{http://inspire.ec.europa.eu/schemas/tn/4.0}MaintenanceAuthority');
INSERT INTO so.feature_types  (id,qname) VALUES (48,'{http://inspire.ec.europa.eu/schemas/tn/4.0}MarkerPost');
INSERT INTO so.feature_types  (id,qname) VALUES (49,'{http://inspire.ec.europa.eu/schemas/tn/4.0}OwnerAuthority');
INSERT INTO so.feature_types  (id,qname) VALUES (50,'{http://inspire.ec.europa.eu/schemas/tn/4.0}RestrictionForVehicles');
INSERT INTO so.feature_types  (id,qname) VALUES (51,'{http://inspire.ec.europa.eu/schemas/tn/4.0}TrafficFlowDirection');
INSERT INTO so.feature_types  (id,qname) VALUES (52,'{http://inspire.ec.europa.eu/schemas/tn/4.0}TransportNetwork');
INSERT INTO so.feature_types  (id,qname) VALUES (53,'{http://inspire.ec.europa.eu/schemas/tn/4.0}VerticalPosition');
INSERT INTO so.feature_types  (id,qname) VALUES (54,'{http://www.opengis.net/gml/3.2}DirectedObservation');
INSERT INTO so.feature_types  (id,qname) VALUES (55,'{http://www.opengis.net/gml/3.2}DirectedObservationAtDistance');
INSERT INTO so.feature_types  (id,qname) VALUES (56,'{http://www.opengis.net/gml/3.2}DynamicFeature');
INSERT INTO so.feature_types  (id,qname) VALUES (57,'{http://www.opengis.net/gml/3.2}DynamicFeatureCollection');
INSERT INTO so.feature_types  (id,qname) VALUES (58,'{http://www.opengis.net/gml/3.2}FeatureCollection');
INSERT INTO so.feature_types  (id,qname) VALUES (59,'{http://www.opengis.net/gml/3.2}GridCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (60,'{http://www.opengis.net/gml/3.2}MultiCurveCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (61,'{http://www.opengis.net/gml/3.2}MultiPointCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (62,'{http://www.opengis.net/gml/3.2}MultiSolidCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (63,'{http://www.opengis.net/gml/3.2}MultiSurfaceCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (64,'{http://www.opengis.net/gml/3.2}Observation');
INSERT INTO so.feature_types  (id,qname) VALUES (65,'{http://www.opengis.net/gml/3.2}RectifiedGridCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (66,'{http://www.opengis.net/gmlcov/1.0}GridCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (67,'{http://www.opengis.net/gmlcov/1.0}MultiCurveCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (68,'{http://www.opengis.net/gmlcov/1.0}MultiPointCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (69,'{http://www.opengis.net/gmlcov/1.0}MultiSolidCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (70,'{http://www.opengis.net/gmlcov/1.0}MultiSurfaceCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (71,'{http://www.opengis.net/gmlcov/1.0}RectifiedGridCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (72,'{http://www.opengis.net/gmlcov/1.0}ReferenceableGridCoverage');
INSERT INTO so.feature_types  (id,qname) VALUES (73,'{http://www.opengis.net/om/2.0}OM_Observation');
INSERT INTO so.feature_types  (id,qname) VALUES (74,'{http://www.opengis.net/sampling/2.0}SF_SamplingFeatureCollection');
INSERT INTO so.feature_types  (id,qname) VALUES (75,'{http://www.opengis.net/samplingSpatial/2.0}SF_SpatialSamplingFeature');
INSERT INTO so.feature_types  (id,qname) VALUES (76,'{http://www.opengis.net/samplingSpecimen/2.0}SF_Specimen');
CREATE TABLE so.gml_objects (id serial PRIMARY KEY, gml_id text UNIQUE NOT NULL, ft_type smallint REFERENCES so.feature_types , binary_object bytea);
COMMENT ON TABLE so.gml_objects IS 'All objects (features and geometries)';
SELECT ADDGEOMETRYCOLUMN('so', 'gml_objects','gml_bounded_by','0','GEOMETRY',2);
ALTER TABLE so.gml_objects ADD CONSTRAINT gml_objects_geochk CHECK (ST_IsValid(gml_bounded_by));
CREATE INDEX gml_objects_sidx ON so.gml_objects  USING GIST (gml_bounded_by);
